package main

import (
	"crypto/subtle"
	"encoding/json"
	"log/slog"
	"net/http"
	"strings"
	"unicode"
)

const maxBodySize = 1024 // 1 KiB — more than enough for the tiny JSON payload

func registerHandlers(mux *http.ServeMux, client *MailxClient) {
	mux.HandleFunc("GET /health", handleHealth)
	mux.HandleFunc("POST /api/v1/aliases", handleCreateAlias(client))
}

func handleHealth(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}

func handleCreateAlias(client *MailxClient) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")

		token, ok := strings.CutPrefix(r.Header.Get("Authorization"), "Bearer ")
		if !ok || token == "" {
			w.WriteHeader(http.StatusUnauthorized)
			json.NewEncoder(w).Encode(map[string]string{"error": "unauthorized"})
			return
		}

		if subtle.ConstantTimeCompare([]byte(token), []byte(client.cfg.BridgeKey)) != 1 {
			w.WriteHeader(http.StatusUnauthorized)
			json.NewEncoder(w).Encode(map[string]string{"error": "unauthorized"})
			return
		}

		// Bitwarden (addy.io mode) sends:
		//   { "domain": "<user input from Email domain field>",
		//     "description": "Generated by Bitwarden." }
		// We use the "domain" value as the alias description in Mailx so users
		// can identify which alias belongs to which service.
		r.Body = http.MaxBytesReader(w, r.Body, maxBodySize)
		var body struct {
			Domain      string `json:"domain"`
			Description string `json:"description"`
		}
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			w.WriteHeader(http.StatusBadRequest)
			json.NewEncoder(w).Encode(map[string]string{"error": "invalid request body"})
			return
		}

		if body.Domain == "" {
			w.WriteHeader(http.StatusUnprocessableEntity)
			json.NewEncoder(w).Encode(map[string]string{"error": "domain is required"})
			return
		}

		description := sanitize(body.Domain, 200)

		slog.Info("creating alias", "description", description)

		alias, err := client.CreateAlias(r.Context(), description)
		if err != nil {
			slog.Error("failed to create alias", "description", description, "error", err)
			w.WriteHeader(http.StatusBadGateway)
			json.NewEncoder(w).Encode(map[string]string{"error": "failed to create alias"})
			return
		}

		slog.Info("alias created", "description", description, "alias", alias)

		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]any{
			"data": map[string]string{
				"email": alias,
			},
		})
	}
}

// sanitize truncates s to maxLen runes and replaces control characters
// with '?' to prevent log injection.
func sanitize(s string, maxLen int) string {
	runes := []rune(s)
	if len(runes) > maxLen {
		runes = runes[:maxLen]
	}
	for i, r := range runes {
		if unicode.IsControl(r) {
			runes[i] = '?'
		}
	}
	return string(runes)
}
